-- MySQL Script generated by MySQL Workbench
-- 10/27/15 15:24:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema workflow
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema workflow
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `workflow` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `workflow` ;

-- -----------------------------------------------------
-- Table `workflow`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow`.`usuarios` (
  `id_usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `login` VARCHAR(20) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `senha` VARCHAR(30) NOT NULL COMMENT '',
  `nome` VARCHAR(20) NOT NULL COMMENT '',
  `sobrenome` VARCHAR(60) NULL COMMENT '',
  `telefone` VARCHAR(15) NULL COMMENT '',
  `telefone_comercial` VARCHAR(15) NULL COMMENT '',
  `celular` VARCHAR(16) NULL COMMENT '',
  `ajuda` TINYINT(1) NULL DEFAULT 1 COMMENT '1 - > Exibe as dicas de ajuda no site\n0 -> Não exibe as dicas de ajuda no site',
  `foto` VARCHAR(120) NULL COMMENT '',
  `cep` VARCHAR(8) NULL COMMENT '',
  `rua` VARCHAR(45) NULL COMMENT '',
  `numero` VARCHAR(6) NULL COMMENT '',
  `complemento` VARCHAR(20) NULL COMMENT '',
  `bairro` VARCHAR(40) NULL COMMENT '',
  `cidade` VARCHAR(40) NULL COMMENT '',
  `estado` VARCHAR(2) NULL COMMENT '',
  PRIMARY KEY (`id_usuario`, `login`)  COMMENT '',
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC)  COMMENT '',
  UNIQUE INDEX `login_UNIQUE` (`login` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workflow`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow`.`empresa` (
  `id_empresa` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(40) NOT NULL COMMENT '',
  `cnpj` VARCHAR(18) NULL COMMENT '',
  `site` VARCHAR(40) NULL COMMENT '',
  `telefone` VARCHAR(15) NULL COMMENT '',
  `logo` VARCHAR(120) NULL COMMENT '',
  `cep` VARCHAR(8) NULL COMMENT '',
  `rua` VARCHAR(45) NULL COMMENT '',
  `numero` VARCHAR(6) NULL COMMENT '',
  `complemento` VARCHAR(20) NULL COMMENT '',
  `bairro` VARCHAR(40) NULL COMMENT '',
  `cidade` VARCHAR(40) NULL COMMENT '',
  `estado` VARCHAR(2) NULL COMMENT '',
  `data` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`id_empresa`)  COMMENT '',
  UNIQUE INDEX `id_empresa_UNIQUE` (`id_empresa` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workflow`.`usuario_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow`.`usuario_empresa` (
  `id_usuario_empresa` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `usuarios_id_usuario` INT NOT NULL COMMENT '',
  `empresa_id_empresa` INT NOT NULL COMMENT '',
  `tipo` INT NOT NULL COMMENT '0 -> Administrador da empresa\n1 -> Colaborador com todos privilégios\n2 -> Colaborador com privilégios restritos\n',
  PRIMARY KEY (`id_usuario_empresa`)  COMMENT '',
  UNIQUE INDEX `id_usuario-empresa_UNIQUE` (`id_usuario_empresa` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workflow`.`caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow`.`caixa` (
  `id_caixa` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `empresa_id_empresa` INT NOT NULL COMMENT '',
  `usuario_id_usuario` INT NOT NULL COMMENT '',
  `categorias_id_categoria` INT NOT NULL COMMENT '',
  `valor` DECIMAL(10) NOT NULL COMMENT '',
  `nome` VARCHAR(40) NULL COMMENT '',
  `data` TIMESTAMP NULL COMMENT '',
  `descricao` TEXT(400) NULL COMMENT '',
  PRIMARY KEY (`id_caixa`)  COMMENT '',
  UNIQUE INDEX `id_caixa_UNIQUE` (`id_caixa` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workflow`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow`.`categorias` (
  `id_categoria` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `empresa_id_empresa` INT NOT NULL COMMENT '',
  `nome` VARCHAR(40) NOT NULL COMMENT '',
  `descrição` TEXT(400) NULL COMMENT '',
  PRIMARY KEY (`id_categoria`)  COMMENT '',
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_categoria` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workflow`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow`.`cliente` (
  `id_cliente` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `empresa_id_empresa` INT NOT NULL COMMENT '',
  `nome` VARCHAR(40) NOT NULL COMMENT '',
  `cnpj` VARCHAR(18) NULL COMMENT '',
  `cpf` VARCHAR(14) NULL COMMENT '',
  `cep` VARCHAR(8) NULL COMMENT '',
  `rua` VARCHAR(45) NULL COMMENT '',
  `numero` VARCHAR(6) NULL COMMENT '',
  `complemento` VARCHAR(20) NULL COMMENT '',
  `bairro` VARCHAR(40) NULL COMMENT '',
  `cidade` VARCHAR(40) NULL COMMENT '',
  `estado` VARCHAR(2) NULL COMMENT '',
  `telefone` VARCHAR(15) NULL COMMENT '',
  `telefone2` VARCHAR(15) NULL COMMENT '',
  `celular` VARCHAR(16) NULL COMMENT '',
  `representante` VARCHAR(40) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `email2` VARCHAR(45) NULL COMMENT '',
  `site` VARCHAR(40) NULL COMMENT '',
  `cadastro` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id_cliente`)  COMMENT '',
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_cliente` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workflow`.`relacionamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow`.`relacionamento` (
  `id_relacionamento` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `empresa_id_empresa` INT NOT NULL COMMENT '',
  `usuarios_id_usuario` INT NOT NULL COMMENT '',
  `mostrar` INT NOT NULL DEFAULT 0 COMMENT '0 -> Somente para o usuário\n1 -> Somente para administradores da empresa\n2 -> Todos da empresa',
  `data_agendamento` TIMESTAMP NOT NULL COMMENT '',
  `tipo` INT NULL COMMENT '0 -> Contato\n1 -> Visita',
  `data` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`id_relacionamento`)  COMMENT '',
  UNIQUE INDEX `id_relacionamento_UNIQUE` (`id_relacionamento` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workflow`.`orcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow`.`orcamento` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workflow`.`operacional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow`.`operacional` (
  `id_servico` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `usuarios_id_usuario` INT NOT NULL COMMENT '',
  `empresa_id_empresa` INT NOT NULL COMMENT '',
  `nome` VARCHAR(30) NOT NULL COMMENT '',
  `data` TIMESTAMP NULL COMMENT '',
  `previsao` TIMESTAMP NULL COMMENT '',
  `inicio` TIMESTAMP NULL COMMENT '',
  `termino` TIMESTAMP NULL COMMENT '',
  `observacoes` TEXT(400) NULL COMMENT '',
  PRIMARY KEY (`id_servico`)  COMMENT '',
  UNIQUE INDEX `id_servico_UNIQUE` (`id_servico` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workflow`.`etapas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow`.`etapas` (
  `id_etapa` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `operacional_id_servico` INT NOT NULL COMMENT '',
  `usuarios_id_usuario` INT NOT NULL COMMENT '',
  `nome` VARCHAR(40) NOT NULL COMMENT '',
  `descricao` TEXT(400) NULL COMMENT '',
  `data` TIMESTAMP NULL COMMENT '',
  `inicio` TIMESTAMP NULL COMMENT '',
  `previsao` TIMESTAMP NULL COMMENT '',
  `termino` TIMESTAMP NULL COMMENT '',
  `comissionamento` TEXT(400) NULL COMMENT '',
  `concluido` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`id_etapa`)  COMMENT '',
  UNIQUE INDEX `id_etapa_UNIQUE` (`id_etapa` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workflow`.`andamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow`.`andamento` (
  `id_andamento` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `id_etapa` INT NOT NULL COMMENT '',
  `usuarios_id_usuario` INT NOT NULL COMMENT '',
  `medicao` INT NOT NULL COMMENT '',
  `data` TIMESTAMP NULL COMMENT '',
  `observacoes` TEXT(400) NULL COMMENT '',
  `data_cadastro` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`id_andamento`)  COMMENT '',
  UNIQUE INDEX `id_andamento_UNIQUE` (`id_andamento` ASC)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
